name: dev

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main

      - name: install nvm 
        run: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 

      - name: install nvm
        run: source ~/.bashrc
        
      - name: install nvm
        run: nvm install 20   

      - name: npm i
        run: npm i

      - name: npm run build
        run: npm run build      

      - name: kill previous server
        run: sudo bash kill

      - name: npm run start
        run: npm run start       
