name: dev

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - name: all
        run: |
          cd /home/server/reps/video-summarization
          git reset --hard origin/main
          git pull
          npm install
          npm run build
          pm2 delete videosummary
          pm2 --name videosummary start npm -- start
    
