name: dev

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - name: cd to folder
        run: cd /home/server/reps/video-summarization

      - name: pull
        run: git reset --hard origin/main  

      - name: pull
        run: git pull

      - name: npm i
        run: npm i

      - name: npm run build
        run: npm run build      

      - name: kill previous server
        run: sudo bash kill

      - name: npm run start
        run: sudo bash start
    
