name: dev

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main

      - name: nvm change version
        run: source ~/.bashrc

      - name: nvm change version
        run: nvm use 20  

      - name: nvm change version
        run: echo echo "$(node -v)"

      - name: npm i
        run: npm i

      - name: npm run build
        run: npm run build      

      - name: kill previous server
        run: sudo bash kill

      - name: npm run start
        run: npm run start       
