name: dev

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main

      - name: test nvm command
        run: export NVM_DIR="$HOME/.nvm"

      - name: test nvm command
        run: source "$NVM_DIR/nvm.sh"

      - name: nvm change version
        run: echo "$(node -v)"

      - name: nvm change version
        run: echo "$(nvm list)"  

      - name: npm i
        run: npm i

      - name: npm run build
        run: npm run build      

      - name: kill previous server
        run: sudo bash kill

      - name: npm run start
        run: npm run start       
